### ISSUE TITLE
Change Engine jobs on Jenkins

### ISSUE THREAD

**Issue by daniviga** [gem/oq-infrastructure#30]
Since we moved our packages to Python 3 we can turn off tests on Jenkins for the Engine on Linux.

@micheles proposed to keep just the nightly build to test and generate nightly packages.
I propose to keep at least a demo with and without celery to test that configurations have been deployed properly by the packages (plus all the other business regarding the packages).

@micheles what you want to do with Python 2.7? We are not running tests against it right now.

**Comment by micheles** [comment]
Actually I proposed to keep the nightly build *identical* to how it is now (i.e. running all tests and one demo before releasing a package). I would just remove the "build on merge" flag.
Notice that there is a repo on travis called oq-engine-celery, so celery is tested every day.

**Comment by daniviga** [comment]
@nastasi-oq if it's ok for you I'll disable the polling in master_oq-engine

**Comment by daniviga** [comment]
Done:
- `master_oq-engine` runs only nightly
- `macos/master_oq-engine` runs at every SCM change and is also triggered by `master_oq-engine`
- `windows/master_oq-engine` runs at every SCM change and is also triggered by `master_oq-engine`
