### ISSUE TITLE
Check missing repo in the GitHub mirror

### ISSUE THREAD

**Issue by daniviga** [gem/oq-infrastructure#41]
Like https://github.com/gem/hazard_scenario_database
Should we need to add also some of the GEMScienceTools repo? (oq-mbt...)

@mmpagani @raoanirudh please let me known any GitHub repo that you want to mirror here https://mirror.openquake.org/git/ (just code, no issues ATM)

**Comment by daniviga** [comment]
https://github.com/gem/hazard_scenario_database

**Comment by daniviga** [comment]
https://github.com/gem/ged4all

**Comment by raoanirudh** [comment]
rmtk, rmtk_docs, rmtk_data are all already mirrored. No additional risk repos to mirror.

**Comment by daniviga** [comment]
Thanks @raoanirudh
